const economicsTerms = [
    { term: "asset", hint: "Something of value owned." },
    { term: "bribe", hint: "Illicit payment to influence." },
    { term: "buyer", hint: "Person purchasing goods/services." },
    { term: "chart", hint: "Visual data representation." },
    { term: "claim", hint: "Demand for something (like insurance)." },
    { term: "costs", hint: "Expenses incurred." },
    { term: "crude", hint: "Unrefined oil, a commodity." },
    { term: "deals", hint: "Business transactions." },
    { term: "debit", hint: "Entry recording money owed." },
    { term: "dutch", hint: "Economic auction type." },
    { term: "funds", hint: "Money for a purpose." },
    { term: "goods", hint: "Physical products." },
    { term: "grant", hint: "Financial aid." },
    { term: "gross", hint: "Total before deductions." },
    { term: "hired", hint: "Employed for work." },
    { term: "index", hint: "Statistical economic measure." },
    { term: "input", hint: "Resources used in production." },
    { term: "labor", hint: "Human work effort." },
    { term: "lease", hint: "Contract for use of asset." },
    { term: "legal", hint: "Conforming to laws." },
    { term: "loose", hint: "Can imply loose monetary policy." },
    { term: "macro", hint: "Macroeconomics - broad economy." },
    { term: "maker", hint: "Producer of goods." },
    { term: "mines", hint: "Sources of natural resources." },
    { term: "money", hint: "Medium of exchange." },
    { term: "offer", hint: "Proposed price for sale." },
    { term: "price", hint: "Amount paid for goods/services." },
    { term: "rates", hint: "Interest or exchange percentages." },
    { term: "rents", hint: "Payments for temporary use." },
    { term: "sales", hint: "Transactions exchanging goods for money." },
    { term: "share", hint: "Unit of ownership." },
    { term: "spend", hint: "Use money to buy." },
    { term: "stock", hint: "Equity investment." },
    { term: "tarif", hint: "Tax on imports/exports." },
    { term: "token", hint: "Digital or physical unit of value." },
    { term: "trade", hint: "Exchange of goods/services." },
    { term: "trend", hint: "Direction of change." },
    { term: "value", hint: "Worth of something." },
    { term: "wages", hint: "Payment for labor." },
    { term: "worth", hint: "Equivalent in value." },
    { term: "yield", hint: "Return on investment." },
    { term: "arbit", hint: "Short for arbitrage." },
    { term: "block", hint: "Large trade quantity." },
    { term: "cycle", hint: "Economic pattern." },
    { term: "delta", hint: "Rate of change in finance." },
    { term: "gamma", hint: "Second derivative in options." },
    { term: "holds", hint: "Retains assets." },
    { term: "lends", hint: "Provides loans." },
    { term: "merch", hint: "Commercial goods." },
    { term: "pacts", hint: "Trade agreements." },
    { term: "point", hint: "Percentage unit." },
    { term: "prime", hint: "Best interest rate." },
    { term: "quota", hint: "Production limit." },
    { term: "rally", hint: "Market upswing." },
    { term: "repay", hint: "Return borrowed money." },
    { term: "risks", hint: "Potential losses." },
    { term: "royal", hint: "Patent payments." },
    { term: "sacks", hint: "Colloquial for money." },
    { term: "saves", hint: "Reserves funds." },
    { term: "scale", hint: "Pricing levels." },
    { term: "sells", hint: "Offloads goods." },
    { term: "slump", hint: "Economic decline." },
    { term: "spike", hint: "Sudden price rise." },
    { term: "stash", hint: "Hidden savings." },
    { term: "surge", hint: "Rapid increase." },
    { term: "swaps", hint: "Financial exchanges." },
    { term: "theta", hint: "Time decay in options." },
    { term: "tithe", hint: "Religious tax." },
    { term: "tolls", hint: "Usage fees." },
    { term: "tills", hint: "Cash registers." },
    { term: "vault", hint: "Secure storage." },
    { term: "waste", hint: "Misused resources." },
    { term: "whale", hint: "Big investor." }
];
